spring.application.name=sentinel-core

# Порт, на котором будет работать наше Java-приложение
server.port=8080

# Настройки подключения к Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Настройки Консьюмера (Слушателя)
spring.kafka.consumer.group-id=sentinel-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Настройки Продюсера (Отправителя)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Логирование (чтобы видеть в консоли, что происходит)
logging.level.com.sentinel=DEBUG
logging.level.org.springframework.kafka=INFO